---
jobs:
- name: build-container-image
  serial: true
  plan:
  - do:
    - get: src
      trigger: true
    - get: deploy-src
      trigger: true
    - task: build
      file: deploy-src/ci/build.yml
    - put: img
      params:
        build: output
        tag_file: src/.git/ref
      get_params: {skip_download: true}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: cloudwatch-exporter-deploy-d
  serial: true
  plan:
  - do:
    - get: src
      passed: [build-container-image]
    - get: deploy-src
      trigger: true
    - get: img
      passed: [build-container-image]
      params: {skip_download: true}
      trigger: true
    - get: ca
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV: "d"
        JUMPBOX_SSH_KEY: ((jumpbox-key.private_key))
        JUMPBOX_SSH_PORT: ((jumpbox-port))
        JUMPBOX_SSH_L_HOST: ((jumpbox-l-host))
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
resources:
- name: src
  type: git
  source:
    uri: https://github.com/govau/cga_cloudwatch_exporter
    branch: master
- name: deploy-src
  type: git
  source:
    uri: https://github.com/govau/cga-deploy-cloudwatch-exporter
    branch: master
- name: img
  type: docker-image
  source:
    repository: ((aws_repository))
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
- name: ca
  type: git
  source:
    branch: master
    paths:
    - terraform/sshca-ca.pub
    private_key: ((ops-git-deploy-key.private_key))
    uri: git@github.com:AusDTO/ops.git
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource