groups: []
resources:
- name: src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga_cloudwatch_exporter
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-cloudwatch-exporter
- name: img
  type: docker-image
  source:
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    repository: ((aws_repository))
- name: ca
  type: git
  source:
    branch: master
    paths:
    - terraform/sshca-ca.pub
    private_key: ((ops-git-deploy-key.private_key))
    uri: git@github.com:AusDTO/ops.git
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: build-image
  serial: true
  plan:
  - do:
    - get: src
      version:
        ref: 9dc6131338e3b675016e79f81f02eeb5a1e8e559
    - get: deploy-src
      trigger: true
    - task: prep-for-build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: 3.8
        run:
          path: sh
          args:
          - -c
          - |
            cp -rf src/* build
            cp deploy-src/Dockerfile build
        inputs:
        - name: src
        - name: deploy-src
        outputs:
        - name: build
    - put: img
      params:
        build: build
        tag_as_latest: true
        tag_file: src/.git/ref
      get_params:
        skip_download: true
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-d
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - build-image
    - get: deploy-src
      passed:
      - build-image
    - get: img
      passed:
      - build-image
      trigger: true
      params:
        skip_download: true
    - get: ca
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV: d
        JUMPBOX_SSH_KEY: ((jumpbox-key.private_key))
        JUMPBOX_SSH_L_HOST: ((jumpbox-l-host))
        JUMPBOX_SSH_PORT: ((jumpbox-port))
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
