groups: []
resources:
- name: charts
  type: git
  source:
    branch: master
    paths:
    - stable/prometheus-cloudwatch-exporter/**
    uri: https://github.com/helm/charts
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-cloudwatch-exporter
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: deploy-common
  serial: true
  plan:
  - do:
    - get: deploy-src
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy-common.yml
      params:
        KUBECONFIG_JSON: ((kubeconfig_json))
- name: deploy-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: charts
    - get: deploy-src
    - task: deploy-g
      file: deploy-src/ci/deploy.yml
      params:
        ENV_NAME: g
        KUBECONFIG_JSON: ((kubeconfig_json))
    - task: smoke-test-g
      file: deploy-src/ci/smoke-test.yml
      params:
        ENV_NAME: g
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: delete-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: delete
      file: deploy-src/ci/delete.yml
      params:
        ENV_NAME: g
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-b
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV_NAME: b
        KUBECONFIG_JSON: ((kubeconfig_json))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        ENV_NAME: b
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-d
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV_NAME: d
        KUBECONFIG_JSON: ((kubeconfig_json))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        ENV_NAME: d
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-l
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV_NAME: l
        KUBECONFIG_JSON: ((kubeconfig_json))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        ENV_NAME: l
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-t
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV_NAME: t
        KUBECONFIG_JSON: ((kubeconfig_json))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        ENV_NAME: t
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-y
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV_NAME: "y"
        KUBECONFIG_JSON: ((kubeconfig_json))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        ENV_NAME: "y"
        KUBECONFIG_JSON: ((kubeconfig_json))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: notify
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-b
      - deploy-d
      - deploy-l
      - deploy-t
      - deploy-y
      trigger: true
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $BUILD_PIPELINE_NAME deploy-prod SUCCESS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
