groups: []
resources:
- name: src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga_cloudwatch_exporter
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-cloudwatch-exporter
- name: img
  type: docker-image
  source:
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    repository: ((aws_repository))
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: build-image
  serial: true
  plan:
  - do:
    - get: src
    - get: deploy-src
      trigger: true
    - put: img
      params:
        build: src
        tag_as_latest: true
        tag_file: src/.git/ref
      get_params:
        skip_download: true
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-d
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - build-image
    - get: deploy-src
      passed:
      - build-image
    - get: img
      passed:
      - build-image
      trigger: true
      params:
        skip_download: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ENV: d
        KUBECONFIG: ((kubeconfig))
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: ship-it
  serial: true
  plan:
    - get: src
      passed:
      - deploy-d
    - get: deploy-src
      passed:
      - deploy-d
    - get: img
      passed:
      - deploy-d
      params:
        skip_download: true
- name: deploy-y
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - ship-it
    - get: deploy-src
      passed:
      - ship-it
    - get: img
      passed:
      - ship-it
      trigger: true
      params:
        skip_download: true
    - task: deploy-y
      file: deploy-src/ci/deploy.yml
      params:
        ENV: "y"
        KUBECONFIG: ((kubeconfig))
    - task: deploy-b
      file: deploy-src/ci/deploy.yml
      params:
        ENV: b
        KUBECONFIG: ((kubeconfig))
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-b
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - ship-it
    - get: deploy-src
      passed:
      - ship-it
    - get: img
      passed:
      - ship-it
      trigger: true
      params:
        skip_download: true
    - task: deploy-b
      file: deploy-src/ci/deploy.yml
      params:
        ENV: b
        KUBECONFIG: ((kubeconfig))
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>


